name: PULL REQUEST ON FORK REPOSITORY

on:
  push:
    branches:
      -  main

jobs:
  pdps:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT REPO URL
        run: |
          echo "REPO_URL ${{ vars.REPO_URL }}"
          echo "REPO_TOKEN ${{ secrets.REPO_TOKEN }}"
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPO_URL }}
          token: ${{ secrets.REPO_TOKEN }}
          ref: ${{ vars.REPO_BRANCH }}
      - name: Setup Git Config
        run: |
          git config user.name 'floo'
          git config user.email 'floo@users.noreply.github.com'
      - name: Add Main Repo As Remote
        run: |
          git remote add origin-core https://github.com/lubab-floo/parent-repo.git
          git fetch origin-core
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Pull Origin
        run: |
          git merge origin-core/main ${{ vars.REPO_BRANCH }} --strategy-option theirs
          git push origin ${{ vars.REPO_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_TOKEN }}
          title: Update ONEGA CORE
          body: "Update ONEGA CORE code"
          labels: "update-core"
          reviewers: ${{ vars.REPO_REVIEWER }}
          branch: ${{ vars.REPO_BRANCH }}
